name: sayfood
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  chewie: ^1.7.0
  flutter_svg: ^2.0.7
  video_player: ^2.7.0
  flappy_search_bar_ns: ^2.0.2
  flutter_staggered_grid_view: ^0.4.1
  velocity_x: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/anim/
    - assets/icons/
    - assets/images/