// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArk0n-22TeGd-kv5gdRzSaEtbcST1prks',
    appId: '1:767749225886:web:df1982d6bb35d88cb3aa8f',
    messagingSenderId: '767749225886',
    projectId: 'sayfood-b0919',
    authDomain: 'sayfood-b0919.firebaseapp.com',
    storageBucket: 'sayfood-b0919.appspot.com',
    measurementId: 'G-RY2YCQH85S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4vTAop6bMBgIqxH9_hvT4zKcUgt6_isU',
    appId: '1:767749225886:android:65afaec760fa4a86b3aa8f',
    messagingSenderId: '767749225886',
    projectId: 'sayfood-b0919',
    storageBucket: 'sayfood-b0919.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALg4MiLjfDHrQVlJ3W2uQ0vMhcpYgVzjA',
    appId: '1:767749225886:ios:b792357cc9782fbbb3aa8f',
    messagingSenderId: '767749225886',
    projectId: 'sayfood-b0919',
    storageBucket: 'sayfood-b0919.appspot.com',
    iosBundleId: 'com.example.sayfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALg4MiLjfDHrQVlJ3W2uQ0vMhcpYgVzjA',
    appId: '1:767749225886:ios:da50b38a3fed4504b3aa8f',
    messagingSenderId: '767749225886',
    projectId: 'sayfood-b0919',
    storageBucket: 'sayfood-b0919.appspot.com',
    iosBundleId: 'com.example.sayfood.RunnerTests',
  );
}
